
package com.redknee.util.crmapi.soap.mobilenumbers.mobilenumbers_v2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.redknee.util.crmapi.soap.common.xsd._2008._08.GenericParameter;
import com.redknee.util.crmapi.soap.common.xsd._2011._05.CRMRequestHeader;
import com.redknee.util.crmapi.soap.mobilenumbers.xsd._2011._07.MobileNumber;
import com.redknee.util.crmapi.soap.mobilenumbers.xsd._2011._07.MobileNumberQueryResult;
import com.redknee.util.crmapi.soap.mobilenumbers.xsd._2011._07.PortingTypeReference;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MobileNumbersPortType_v2_0", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/MobileNumbers-v2.0")
@XmlSeeAlso({
    com.redknee.util.crmapi.soap.common.exception.xsd._2008._08.ObjectFactory.class,
    com.redknee.util.crmapi.soap.common.xsd._2008._08.ObjectFactory.class,
    com.redknee.util.crmapi.soap.common.xsd._2011._05.ObjectFactory.class,
    com.redknee.util.crmapi.soap.common.xsd.common_v1.ObjectFactory.class,
    com.redknee.util.crmapi.soap.common.xsd.common_v2.ObjectFactory.class,
    com.redknee.util.crmapi.soap.mobilenumbers.xsd._2011._07.ObjectFactory.class,
    com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.ObjectFactory.class
})
public interface MobileNumbersPortTypeV20 {


    /**
     * 
     * @param paidType
     * @param groupID
     * @param limit
     * @param header
     * @param pageKey
     * @param state
     * @param isAscending
     * @param parameters
     * @return
     *     returns com.redknee.util.crmapi.soap.mobilenumbers.xsd._2011._07.MobileNumberQueryResult
     * @throws CRMExceptionFault
     */
    @WebMethod(action = "urn:listMobileNumbers")
    @WebResult(targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
    @RequestWrapper(localName = "listMobileNumbers", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0", className = "com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.ListMobileNumbers")
    @ResponseWrapper(localName = "listMobileNumbersResponse", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0", className = "com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.ListMobileNumbersResponse")
    public MobileNumberQueryResult listMobileNumbers(
        @WebParam(name = "header", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        CRMRequestHeader header,
        @WebParam(name = "groupID", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        long groupID,
        @WebParam(name = "state", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        Long state,
        @WebParam(name = "pageKey", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        String pageKey,
        @WebParam(name = "limit", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        int limit,
        @WebParam(name = "isAscending", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        Boolean isAscending,
        @WebParam(name = "parameters", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        List<GenericParameter> parameters,
        @WebParam(name = "paidType", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        Long paidType)
        throws CRMExceptionFault
    ;

    /**
     * 
     * @param identifier
     * @param header
     * @return
     *     returns com.redknee.util.crmapi.soap.mobilenumbers.xsd._2011._07.MobileNumber
     * @throws CRMExceptionFault
     */
    @WebMethod(action = "urn:getMobileNumber")
    @WebResult(targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
    @RequestWrapper(localName = "getMobileNumber", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0", className = "com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.GetMobileNumber")
    @ResponseWrapper(localName = "getMobileNumberResponse", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0", className = "com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.GetMobileNumberResponse")
    public MobileNumber getMobileNumber(
        @WebParam(name = "header", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        CRMRequestHeader header,
        @WebParam(name = "identifier", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        String identifier)
        throws CRMExceptionFault
    ;

    /**
     * 
     * @param identifier
     * @param header
     * @param parameters
     * @param newState
     * @return
     *     returns com.redknee.util.crmapi.soap.mobilenumbers.xsd._2011._07.MobileNumber
     * @throws CRMExceptionFault
     */
    @WebMethod(action = "urn:updateMobileNumberState")
    @WebResult(targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
    @RequestWrapper(localName = "updateMobileNumberState", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0", className = "com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.UpdateMobileNumberState")
    @ResponseWrapper(localName = "updateMobileNumberStateResponse", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0", className = "com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.UpdateMobileNumberStateResponse")
    public MobileNumber updateMobileNumberState(
        @WebParam(name = "header", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        CRMRequestHeader header,
        @WebParam(name = "identifier", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        String identifier,
        @WebParam(name = "newState", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        long newState,
        @WebParam(name = "parameters", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        List<GenericParameter> parameters)
        throws CRMExceptionFault
    ;

    /**
     * 
     * @param identifier
     * @param header
     * @return
     *     returns com.redknee.util.crmapi.soap.mobilenumbers.xsd._2011._07.PortingTypeReference
     * @throws CRMExceptionFault
     */
    @WebMethod(action = "urn:getMobileNumberPortingType")
    @WebResult(targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
    @RequestWrapper(localName = "getMobileNumberPortingType", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0", className = "com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.GetMobileNumberPortingType")
    @ResponseWrapper(localName = "getMobileNumberPortingTypeResponse", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0", className = "com.redknee.util.crmapi.soap.mobilenumbers.xsd.mobilenumbers_v2.GetMobileNumberPortingTypeResponse")
    public PortingTypeReference getMobileNumberPortingType(
        @WebParam(name = "header", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        CRMRequestHeader header,
        @WebParam(name = "identifier", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/xsd/MobileNumbers-v2.0")
        String identifier)
        throws CRMExceptionFault
    ;

}
