
package com.redknee.util.crmapi.soap.mobilenumbers.mobilenumbers_v2;

import javax.xml.ws.WebFault;
import com.redknee.util.crmapi.soap.common.exception.xsd._2008._08.CRMException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CRMException", targetNamespace = "http://soap.crmapi.util.redknee.com/common/exception/xsd/2008/08")
public class CRMExceptionFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CRMException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CRMExceptionFault(String message, CRMException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CRMExceptionFault(String message, CRMException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.redknee.util.crmapi.soap.common.exception.xsd._2008._08.CRMException
     */
    public CRMException getFaultInfo() {
        return faultInfo;
    }

}
