
package com.redknee.util.crmapi.soap.mobilenumbers.mobilenumbers_v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MobileNumberService", targetNamespace = "http://soap.crmapi.util.redknee.com/mobilenumbers/MobileNumbers-v2.0", wsdlLocation = "http://pun1lvm19:11648/RedkneeSoap_v3_0/services/MobileNumberService?wsdl")
public class MobileNumberService
    extends Service
{

    private final static URL MOBILENUMBERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOBILENUMBERSERVICE_EXCEPTION;
    private final static QName MOBILENUMBERSERVICE_QNAME = new QName("http://soap.crmapi.util.redknee.com/mobilenumbers/MobileNumbers-v2.0", "MobileNumberService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pun1lvm19:11648/RedkneeSoap_v3_0/services/MobileNumberService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOBILENUMBERSERVICE_WSDL_LOCATION = url;
        MOBILENUMBERSERVICE_EXCEPTION = e;
    }

    public MobileNumberService() {
        super(__getWsdlLocation(), MOBILENUMBERSERVICE_QNAME);
    }

    public MobileNumberService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOBILENUMBERSERVICE_QNAME, features);
    }

    public MobileNumberService(URL wsdlLocation) {
        super(wsdlLocation, MOBILENUMBERSERVICE_QNAME);
    }

    public MobileNumberService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOBILENUMBERSERVICE_QNAME, features);
    }

    public MobileNumberService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileNumberService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MobileNumbersPortTypeV20
     */
    @WebEndpoint(name = "MobileNumbersSOAP11port_http")
    public MobileNumbersPortTypeV20 getMobileNumbersSOAP11PortHttp() {
        return super.getPort(new QName("http://soap.crmapi.util.redknee.com/mobilenumbers/MobileNumbers-v2.0", "MobileNumbersSOAP11port_http"), MobileNumbersPortTypeV20.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileNumbersPortTypeV20
     */
    @WebEndpoint(name = "MobileNumbersSOAP11port_http")
    public MobileNumbersPortTypeV20 getMobileNumbersSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.crmapi.util.redknee.com/mobilenumbers/MobileNumbers-v2.0", "MobileNumbersSOAP11port_http"), MobileNumbersPortTypeV20.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOBILENUMBERSERVICE_EXCEPTION!= null) {
            throw MOBILENUMBERSERVICE_EXCEPTION;
        }
        return MOBILENUMBERSERVICE_WSDL_LOCATION;
    }

}
